// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DefeatMessage.proto

public final class DefeatMessageOuterClass {
  private DefeatMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DefeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DefeatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .DefeatMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .DefeatMessage.Type type = 1;</code>
     */
    DefeatMessageOuterClass.DefeatMessage.Type getType();

    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    boolean hasCallMessage();
    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    CallMessageOuterClass.CallMessage getCallMessage();
    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder();

    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    boolean hasBackMessage();
    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    BackMessageOuterClass.BackMessage getBackMessage();
    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder();
  }
  /**
   * Protobuf type {@code DefeatMessage}
   */
  public static final class DefeatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DefeatMessage)
      DefeatMessageOrBuilder {
    // Use DefeatMessage.newBuilder() to construct.
    private DefeatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DefeatMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DefeatMessage defaultInstance;
    public static DefeatMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DefeatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DefeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              DefeatMessageOuterClass.DefeatMessage.Type value = DefeatMessageOuterClass.DefeatMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              CallMessageOuterClass.CallMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = callMessage_.toBuilder();
              }
              callMessage_ = input.readMessage(CallMessageOuterClass.CallMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callMessage_);
                callMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              BackMessageOuterClass.BackMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = backMessage_.toBuilder();
              }
              backMessage_ = input.readMessage(BackMessageOuterClass.BackMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(backMessage_);
                backMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DefeatMessageOuterClass.internal_static_DefeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DefeatMessageOuterClass.DefeatMessage.class, DefeatMessageOuterClass.DefeatMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DefeatMessage> PARSER =
        new com.google.protobuf.AbstractParser<DefeatMessage>() {
      public DefeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DefeatMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DefeatMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code DefeatMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CallMessage = 1;</code>
       */
      CallMessage(0, 1),
      /**
       * <code>BackMessage = 2;</code>
       */
      BackMessage(1, 2),
      ;

      /**
       * <code>CallMessage = 1;</code>
       */
      public static final int CallMessage_VALUE = 1;
      /**
       * <code>BackMessage = 2;</code>
       */
      public static final int BackMessage_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return CallMessage;
          case 2: return BackMessage;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DefeatMessageOuterClass.DefeatMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DefeatMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private DefeatMessageOuterClass.DefeatMessage.Type type_;
    /**
     * <code>required .DefeatMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .DefeatMessage.Type type = 1;</code>
     */
    public DefeatMessageOuterClass.DefeatMessage.Type getType() {
      return type_;
    }

    public static final int CALLMESSAGE_FIELD_NUMBER = 2;
    private CallMessageOuterClass.CallMessage callMessage_;
    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    public boolean hasCallMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    public CallMessageOuterClass.CallMessage getCallMessage() {
      return callMessage_;
    }
    /**
     * <code>optional .CallMessage callMessage = 2;</code>
     */
    public CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder() {
      return callMessage_;
    }

    public static final int BACKMESSAGE_FIELD_NUMBER = 3;
    private BackMessageOuterClass.BackMessage backMessage_;
    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    public boolean hasBackMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    public BackMessageOuterClass.BackMessage getBackMessage() {
      return backMessage_;
    }
    /**
     * <code>optional .BackMessage backMessage = 3;</code>
     */
    public BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder() {
      return backMessage_;
    }

    private void initFields() {
      type_ = DefeatMessageOuterClass.DefeatMessage.Type.CallMessage;
      callMessage_ = CallMessageOuterClass.CallMessage.getDefaultInstance();
      backMessage_ = BackMessageOuterClass.BackMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, callMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, backMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, callMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, backMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DefeatMessageOuterClass.DefeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DefeatMessageOuterClass.DefeatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DefeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DefeatMessage)
        DefeatMessageOuterClass.DefeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DefeatMessageOuterClass.internal_static_DefeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DefeatMessageOuterClass.DefeatMessage.class, DefeatMessageOuterClass.DefeatMessage.Builder.class);
      }

      // Construct using DefeatMessageOuterClass.DefeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCallMessageFieldBuilder();
          getBackMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = DefeatMessageOuterClass.DefeatMessage.Type.CallMessage;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (callMessageBuilder_ == null) {
          callMessage_ = CallMessageOuterClass.CallMessage.getDefaultInstance();
        } else {
          callMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (backMessageBuilder_ == null) {
          backMessage_ = BackMessageOuterClass.BackMessage.getDefaultInstance();
        } else {
          backMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DefeatMessageOuterClass.internal_static_DefeatMessage_descriptor;
      }

      public DefeatMessageOuterClass.DefeatMessage getDefaultInstanceForType() {
        return DefeatMessageOuterClass.DefeatMessage.getDefaultInstance();
      }

      public DefeatMessageOuterClass.DefeatMessage build() {
        DefeatMessageOuterClass.DefeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DefeatMessageOuterClass.DefeatMessage buildPartial() {
        DefeatMessageOuterClass.DefeatMessage result = new DefeatMessageOuterClass.DefeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (callMessageBuilder_ == null) {
          result.callMessage_ = callMessage_;
        } else {
          result.callMessage_ = callMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (backMessageBuilder_ == null) {
          result.backMessage_ = backMessage_;
        } else {
          result.backMessage_ = backMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DefeatMessageOuterClass.DefeatMessage) {
          return mergeFrom((DefeatMessageOuterClass.DefeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DefeatMessageOuterClass.DefeatMessage other) {
        if (other == DefeatMessageOuterClass.DefeatMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCallMessage()) {
          mergeCallMessage(other.getCallMessage());
        }
        if (other.hasBackMessage()) {
          mergeBackMessage(other.getBackMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DefeatMessageOuterClass.DefeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DefeatMessageOuterClass.DefeatMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private DefeatMessageOuterClass.DefeatMessage.Type type_ = DefeatMessageOuterClass.DefeatMessage.Type.CallMessage;
      /**
       * <code>required .DefeatMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .DefeatMessage.Type type = 1;</code>
       */
      public DefeatMessageOuterClass.DefeatMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .DefeatMessage.Type type = 1;</code>
       */
      public Builder setType(DefeatMessageOuterClass.DefeatMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .DefeatMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = DefeatMessageOuterClass.DefeatMessage.Type.CallMessage;
        onChanged();
        return this;
      }

      private CallMessageOuterClass.CallMessage callMessage_ = CallMessageOuterClass.CallMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder> callMessageBuilder_;
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public boolean hasCallMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public CallMessageOuterClass.CallMessage getCallMessage() {
        if (callMessageBuilder_ == null) {
          return callMessage_;
        } else {
          return callMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public Builder setCallMessage(CallMessageOuterClass.CallMessage value) {
        if (callMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callMessage_ = value;
          onChanged();
        } else {
          callMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public Builder setCallMessage(
          CallMessageOuterClass.CallMessage.Builder builderForValue) {
        if (callMessageBuilder_ == null) {
          callMessage_ = builderForValue.build();
          onChanged();
        } else {
          callMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public Builder mergeCallMessage(CallMessageOuterClass.CallMessage value) {
        if (callMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              callMessage_ != CallMessageOuterClass.CallMessage.getDefaultInstance()) {
            callMessage_ =
              CallMessageOuterClass.CallMessage.newBuilder(callMessage_).mergeFrom(value).buildPartial();
          } else {
            callMessage_ = value;
          }
          onChanged();
        } else {
          callMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public Builder clearCallMessage() {
        if (callMessageBuilder_ == null) {
          callMessage_ = CallMessageOuterClass.CallMessage.getDefaultInstance();
          onChanged();
        } else {
          callMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public CallMessageOuterClass.CallMessage.Builder getCallMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCallMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      public CallMessageOuterClass.CallMessageOrBuilder getCallMessageOrBuilder() {
        if (callMessageBuilder_ != null) {
          return callMessageBuilder_.getMessageOrBuilder();
        } else {
          return callMessage_;
        }
      }
      /**
       * <code>optional .CallMessage callMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder> 
          getCallMessageFieldBuilder() {
        if (callMessageBuilder_ == null) {
          callMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              CallMessageOuterClass.CallMessage, CallMessageOuterClass.CallMessage.Builder, CallMessageOuterClass.CallMessageOrBuilder>(
                  getCallMessage(),
                  getParentForChildren(),
                  isClean());
          callMessage_ = null;
        }
        return callMessageBuilder_;
      }

      private BackMessageOuterClass.BackMessage backMessage_ = BackMessageOuterClass.BackMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder> backMessageBuilder_;
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public boolean hasBackMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public BackMessageOuterClass.BackMessage getBackMessage() {
        if (backMessageBuilder_ == null) {
          return backMessage_;
        } else {
          return backMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public Builder setBackMessage(BackMessageOuterClass.BackMessage value) {
        if (backMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          backMessage_ = value;
          onChanged();
        } else {
          backMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public Builder setBackMessage(
          BackMessageOuterClass.BackMessage.Builder builderForValue) {
        if (backMessageBuilder_ == null) {
          backMessage_ = builderForValue.build();
          onChanged();
        } else {
          backMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public Builder mergeBackMessage(BackMessageOuterClass.BackMessage value) {
        if (backMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              backMessage_ != BackMessageOuterClass.BackMessage.getDefaultInstance()) {
            backMessage_ =
              BackMessageOuterClass.BackMessage.newBuilder(backMessage_).mergeFrom(value).buildPartial();
          } else {
            backMessage_ = value;
          }
          onChanged();
        } else {
          backMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public Builder clearBackMessage() {
        if (backMessageBuilder_ == null) {
          backMessage_ = BackMessageOuterClass.BackMessage.getDefaultInstance();
          onChanged();
        } else {
          backMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public BackMessageOuterClass.BackMessage.Builder getBackMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getBackMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      public BackMessageOuterClass.BackMessageOrBuilder getBackMessageOrBuilder() {
        if (backMessageBuilder_ != null) {
          return backMessageBuilder_.getMessageOrBuilder();
        } else {
          return backMessage_;
        }
      }
      /**
       * <code>optional .BackMessage backMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder> 
          getBackMessageFieldBuilder() {
        if (backMessageBuilder_ == null) {
          backMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BackMessageOuterClass.BackMessage, BackMessageOuterClass.BackMessage.Builder, BackMessageOuterClass.BackMessageOrBuilder>(
                  getBackMessage(),
                  getParentForChildren(),
                  isClean());
          backMessage_ = null;
        }
        return backMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DefeatMessage)
    }

    static {
      defaultInstance = new DefeatMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DefeatMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DefeatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DefeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DefeatMessage.proto\032\021BackMessage.proto" +
      "\032\021CallMessage.proto\"\242\001\n\rDefeatMessage\022!\n" +
      "\004type\030\001 \002(\0162\023.DefeatMessage.Type\022!\n\013call" +
      "Message\030\002 \001(\0132\014.CallMessage\022!\n\013backMessa" +
      "ge\030\003 \001(\0132\014.BackMessage\"(\n\004Type\022\017\n\013CallMe" +
      "ssage\020\001\022\017\n\013BackMessage\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BackMessageOuterClass.getDescriptor(),
          CallMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_DefeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DefeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DefeatMessage_descriptor,
        new java.lang.String[] { "Type", "CallMessage", "BackMessage", });
    BackMessageOuterClass.getDescriptor();
    CallMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
